[[examples]]
name = "basic"
path = "src/examples/basic.rs"

[package]
name = "rust-net"
version = "0.1.0"
authors = ["Muriel Berehulka <murielberehulka@gmail.com>"]
edition = "2018"

[dependencies.mio]
version = "0.7.11"
features = ["net","os-poll"]